server:
  port: 8761
eureka:
  instance:
    hostname: eureka.firek.cc
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/